### ISSUE TITLE
REL sync strategy with user selected locations seems to fail

### ISSUE THREAD

**Issue by dubdabasoduba** [onaio/fhir-gateway-extension#69]
## Context
- The Related Entity Location (REL) sync strategy added [here](https://github.com/opensrp/fhircore/issues/3052) seems to fail when the `_syncLocations` has a long list.  
- Here is an example of the [request](https://gateway.unicef-mg-eusm-preview.smartregister.org/fhir/Encounter?_count=100&_syncLocations=590cb1f9-4263-4ea5-8216-24c6cb845c86,5c70635b-286d-4a65-8275-3169554b7ee8,ac0140bb-2769-4ca4-96d2-462bb54e7996,eff94f33-c356-4634-8795-d52340706ba9,077b72ab-19f1-44d9-ae27-7b2796a3c1da,25c56dd5-4dca-449d-bf6e-665f90d0ff77,20bef46f-b5f2-490f-beca-d9fa6205be06,f15ff8ab-9475-4356-8363-7f518fdd66ce,c20fa259-1beb-42ad-b186-b8a7d18fc622,493f46d8-6dfe-4505-ab63-9d78c789400e,ee69ce9e-e998-48b0-b3ec-1b5459ee51e0,d452c392-26bc-4fbf-abba-6c2048f12461&_sort=_lastUpdated) that fails on the EUSM project 

## Acceptance criteria
- [ ] All requests with valid parameters should pass
- [ ] All requests with valid parameters should return the required results

**Comment by dubdabasoduba** [comment]
Fixes https://github.com/onaio/fhir-resources/issues/3095

**Comment by lincmba** [comment]
```
<html>
<head><title>414 Request-URI Too Large</title></head>
<body>
<center><h1>414 Request-URI Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
This is the error we get when we hit the API via postman. This was previously resolved by increasing the client header size. The PR attached addresses this.
