### ISSUE TITLE
Only download service points with inventory 

### ISSUE THREAD

**Issue by AnnieMungai** [onaio/fhir-gateway-extension#81]
Currently, on the app, all the service points are downloaded and the user can view all. This number is quite large. To reduce the number of service points users can download and view, improve performance and meet the user requirement as a monitoring tool for supplies, there is a need to filter out all the service points and leave only those with inventory within the accountability period. 

**Required**
- Implement filtering of service points by inventory. 

**Acceptance criteria**
- [ ] Only service points with valid inventory are downloaded and seen on the app register and map views when a user selects a region and district.

**Comment by dubdabasoduba** [comment]
### Technical Implementation
#### Context
- Locations use the location FHIR resource.  
- The Inventory uses the Group FHIR resource. 
- The Linkage between the location and inventory uses the List FHIR resource. 
- Samples of the above can be found here https://github.com/onaio/fhir-resources/issues/3016

#### Implementation
- Enhance the Location Hierarchy endpoint by introducing a filter option that enables filtering of locations based on whether they have assigned inventory.
    - We can use `filterInventory=true/false` as the filter parameters. 
    - If the above parameter is set to true we then have to filter the locations and only return the Locations that have the List resource linking Locations to the Group (inventory)
- Evaluate the performance implications of this filter to the location hierarchy endpoint.

**Comment by dubdabasoduba** [comment]
@lincmba Please update the Engineering implementation Plan and LOE here.
