### ISSUE TITLE
Update the LocationHierarchy endpoint to filter locations by `_lastUpdated` when on `list` mode

### ISSUE THREAD

**Issue by dubdabasoduba** [onaio/fhir-gateway-extension#90]
## Context
- The LocationHierarchy hierarchy endpoint currently returns all the locations every time it is called. While this is good when trying to fetch all the data, it's kinda unnecessary when using it for subsequent sync on the app.  
- We would like to introduce the `_lastUpdated` parameter to solve the above problem.  

## Implementation 
- [ ] This parameter would accept a DateTime and then pass the same to HAPI using the `_lastUpdated` parameter on HAPI.  
- [ ] The parameter should only be relevant if the LocationHierarchy request also has `mode=list`
- [ ] In case the `_lastUpdated` is not set or is empty the endpoint should behave as it does right now which is to fetch everything

## Acceptance Criteria
- [ ] Users should be able to use the `_lastUpdated` parameter after this work is completed
- [ ] In case the `_lastUpdated` is not added the endpoint should work as is right now i.e it should return everything
- [ ] The `_lastUpdated` parameter should only be relevant is the location hierarchy request has `mode=list`

**Comment by lincmba** [comment]
The `_lastUpdated` parameter will be applied as a post-fetch filter to ensure we retrieve the complete hierarchy structure, even if some parent locations do not meet the `_lastUpdated` criteria. Filtering solely at the initial fetch risks missing descendant locations with recent updates that are critical to the hierarchy. For example, if a parent location in the hierarchy is not updated recently, HAPI will exclude it from the results, causing any recently updated children or deeper descendants to also be excluded unintentionally. Post-fetch filtering allows us to gather all locations initially and then apply `_lastUpdated` criteria after ensuring the integrity of the hierarchy is intact.

**Comment by lincmba** [comment]
To implement the `_lastUpdated` filter, we will perform the following steps:

1. Accept the` _lastUpdated `parameter in the LocationHierarchy request. This parameter should be in DateTime format and adhere to the FHIR specification format, e.g., "2024-10-30T09:14:54.122+00:00".
2. Fetch the full location hierarchy based on the provided location and administrative levels, without initially filtering by `_lastUpdated`.
3. Apply the `_lastUpdated` filter after fetching the hierarchy. Iterate through the location results, retaining only those with a meta.lastUpdated value greater than the provided `_lastUpdated` parameter.
4. Return the filtered hierarchy, ensuring that all relevant locations within the requested date boundary are included, maintaining structural completeness and preserving parent-child relationships.
